### ISSUE TITLE
Required validation should be ignored when hideExpression applies (true)

### ISSUE THREAD

**Issue by hassanthegooner** [formly-js/ng-formly#406]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
When a field is hidden using hideExpression, the "required" templateOption should not apply. At the moment, it is still being applied even if the field is hidden. 

**Expected behavior**
Required should be ignored when the hide expression applies

Example JSON below:

``` 
  "fieldGroup": [
                    {
                      "key": "type_of_rigging_for_rescue",
                      "type": "tacheckbox",
                      "templateOptions": {
                        "options": [
                          {
                            "key": "reusable",
                            "value": "Reusable achor"
                          },
                          {
                            "key": "seperate",
                            "value": "Seperate pre rigges system for decending..."
                          },
                          {
                            "key": "others",
                            "value": "Other Type for rescue"
                          }
                        ],
                        "label": "Type of rigging for rescue?",

                      }
                    },
                    {
                      "key": "type_of_rigging_for_rescue.please_specify_other_type",
                      "type": "tatextarea",
                      "isAnswered": false,
                      "answer": "",
                      "defaultValue": "",
                      "hideExpression": "model.type_of_rigging_for_rescue ? (model.type_of_rigging_for_rescue.others ? false : true) : true",
                      "templateOptions": {
                        "label": "Please specify other type",
                        "required": true,
                        "placeholder": "Type here"
                      },     
                    }
                  ]
`

**Comment by aitboudad** [comment]
Hi, I think it is an expected behavior when a field is hidden means it is not part of the form anymore.
To solve your issue you can use custom validation and pass it into the parent field

**Comment by hassanthegooner** [comment]
Hi,

Yes we can probably do that but wouldn't the complexity increase for each nested/connected field? In Formly 1, if the field was hidden then the validation was ignored which to me makes sense and would be a great addition to Formly 2. Are there any plans to add this feature?

**Comment by aitboudad** [comment]
sorry I misread the issue, the validation for hidden field should be ignored, can you tell me what version of `ng-formly` do you use ?

**Comment by hassanthegooner** [comment]
2.0.0-beta.14

**Comment by stephanjust** [comment]
I think I just face the same issue (or a similar one). It appears that formly shows error messages for disabled fields if they're dirty.

I can reliably reproduce it in our local project:
A form with 2 fields, the first being a toggle to disable the other one. If you simply toggle the second field without ever typing in it formly shows no error message. As soon as you type in the second field (so it gets marked as dirty) and you toggle again formly displays an error message even though the field is disabled.

In our case the error message is not even displayed correctly (it's an empty message as there are no errors in the formControl).

**Comment by aitboudad** [comment]
@stephanjust in some case showing error message for disabled filed is useful and I think it's an expected behavior.
Correct me if I'm wrong :)

**Comment by aitboudad** [comment]
fixed by #410

**Comment by aitboudad** [comment]
@hassanthegooner `1.0.0-rc.4` is published, let me know if it's ok for you

**Comment by hassanthegooner** [comment]
It's partially working. 

I have a custom multicheckbox with a very similar implementation to the multicheckbox in Fomly. The only difference in my implementation is that I am attaching a validator to the whole FormGroup:

`
static createControl(model: any, field: FormlyFieldConfig): AbstractControl {
    let controlGroupConfig = field.templateOptions.options.reduce((previous, option) => {
      previous[option.key] = new FormControl(
        model ? model[option.key] : false
      );
      return previous;
    }, {});

    return new FormGroup(controlGroupConfig, field.validators ? field.validators.validation : undefined,
      field.asyncValidators ? field.asyncValidators.validation : undefined, );
  }
` 

I am using a custom validator that works perfectly when there is no hide expression. 
The hide expression works with the standard Angular validators e.g. Required and MaxLength but it doesn't work with my custom validator.

**Comment by aitboudad** [comment]
@hassanthegooner It would be helpful if you can provide me a full example that I can reproduce on my side

**Comment by hassanthegooner** [comment]
@aitboudad in-progress. Thanks

**Comment by hassanthegooner** [comment]
@aitboudad Sorry for taking so long.. finally got the plunker working. Here it is: [plunker](https://plnkr.co/edit/qozmugeETECSq3vYYgjO?p=preview)

**Comment by aitboudad** [comment]
Thanks I can reproduce it, for a quick fix you can check https://github.com/aitboudad/ng2-formly/commit/327399793e8135765478eeedfcce75b00d8d0a38#diff-20a28cc7f674c75babd0efff8e70bb9c

**Comment by hassanthegooner** [comment]
@aitboudad it's not working for me. From what I've noticed, it seems like the hidden FormControl is not being removed from FormGroup (even though it should?)

**Comment by aitboudad** [comment]
@hassanthegooner thanks for the details I'll try to investigate on this as soon as possible

**Comment by aitboudad** [comment]
@hassanthegooner for nested keys the model value in `hideExpression` contains only the parent model value, in order to target the root model in expression you should use the formState:
```ts
hideExpression: 'formState.model.text !== "hello"',
```
Also do not forget to pass the following options in your `formly-form` component.
```ts
options = {
  formState: { model: yourModel, },
};
```

**Comment by aitboudad** [comment]
fixed and published under `1.0.0-rc.5`

**Comment by hassanthegooner** [comment]
Hi,

For me the issue still exists when hiding fields with nested keys even though I'm using formState. I've done some debugging to see what's happening with the FormGroup and detailed my findings below:

### Example JSON ###

```
hiddenFieldGroup: [{
            key: 'data.external.seal_broken.findings.value',
            type: 'input',
            templateOptions: {
                label: 'Is the seal broken?',
                required: true
            }
        },
        {
            key: 'data.external.seal_broken.action_taken.value',
            type: 'input',
            hideExpression: 'formState.model.data.external.seal_broken.findings.value !== "no"',
            templateOptions: {
                label: 'Action taken',
                required: true
            }
        }
    ],
    normalFieldGroup: [{
        key: 'data.external.another_question.findings.value',
        type: 'input',
        templateOptions: {
            label: 'Another question',
            required: true
        }
    }]
```

- Non-hidden field key: `data.external.seal_broken.findings.value`

- Hidden field key: `data.external.seal_broken.action_taken.value`

- Hide expression: `formState.model.data.external.seal_broken.findings.value !== "no"`

### Steps to produce validation errors

1. Before triggering show i.e. hidden field is hidden:
    - The *FormControl* for `data.external.seal_broken.action_taken.value` does not exist at all 👍

2. After triggering the hide expression (value=no) to reveal the hidden field with no further input:
    - *FormControl* with the name of the hidden field key i.e. `data.external.seal_broken.action_taken.value` is added to the root *FormGroup* (?)
    - However, the *FormControl* for `data.external.seal_broken.action_taken.value` does not exist within its parent i.e. the 'value' *FormControl* does not exists inside the 'action_taken' *FormGroup* 👎

3. Triggering a refresh of formly e.g. going to the next fieldGroup and then going back to the correct fieldGroup
    - adds the `data.external.seal_broken.action_taken.value` *FormControl* to its parent i.e. the `value` *FormControl* now exists inside the `action_taken` *FormGroup*. > This is the expected behaviour but it should **not** require the refresh. 😕

4. After triggering the hide expression (value=yes) to hide the hidden field again:
    - *FormControl* with the name of the hidden field key i.e. `data.external.seal_broken.action_taken.value` is removed from the root *FormGroup* but the 'value' *FormControl* is **not** removed from its parent *FormGroup* 'action_taken' 👎

So it looks like the issue is with adding and removing the controls using the nested key names?

I hope that this is enough information but will try to create a plunker anyway. 

Regards

**Comment by aitboudad** [comment]
plunker would be helpful :), thanks!

**Comment by hassanthegooner** [comment]
[Plunker](https://plnkr.co/edit/ZtP12iPx4g474jsyHs2i?p=preview)

**Comment by aitboudad** [comment]
@hassanthegooner well explained :+1: now I see what's happening

**Comment by aitboudad** [comment]
@hassanthegooner can you test my fix https://github.com/formly-js/ng-formly/pull/424

**Comment by hassanthegooner** [comment]
@aitboudad It works! 😎👌🏽

**Comment by aitboudad** [comment]
That's great! and thanks for your patience
