### ISSUE TITLE
How to detect changes of expressionProperties in field class

### ISSUE THREAD

**Issue by HazizKhan** [formly-js/ng-formly#577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Expected behavior**

Lets say if i have two select dropdown fields. one select field has two options 'A' and 'B' and on the basis of the selected option , an api call is made which gets me a list that i need to display as the options in my other select field.

**Comment by aitboudad** [comment]
@HazizKhan do you want something similar to `hidden` changes using (`fieldChanges`), right ?

**Comment by HazizKhan** [comment]
@aitboudad no the field is visible. let me explain we have 2 select boxes select box "1" and select box "2", both select boxes are custom fields (components).
in select box "1" there is 2 options "A" and "B" and options of select box "2" is dependent on select box "1" value. when i select any option from select box "1" then an api call is made with selected value of select box "1" from select box "2" component and in response of api call there is array of options which i want to display as select box "2" options

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-9wekfg?file=app%2Fapp.component.ts

**Comment by HazizKhan** [comment]
@aitboudad Thanks for a quick response :) there is a 1 problem if i set defaultValue of select box "1" then options of select box "2" is empty.

**Comment by aitboudad** [comment]
example updated

**Comment by HazizKhan** [comment]
@aitboudad Thanks but in my case i have many fields and many types of fields and all fields are dynamic so i don't know where my select field is. 

![image](https://user-images.githubusercontent.com/13147389/33322687-e9b864c0-d46b-11e7-9851-06926404adcd.png)

**Comment by aitboudad** [comment]
fixed

**Comment by HazizKhan** [comment]
@aitboudad Thanks Its worked for me now :)

**Comment by uouo690** [comment]
@aitboudad  Hello , I have the same issue and I can still see it  uses the same fixed array index

this.formFields[1].templateOptions.options

I use select inside a repeat element so I can't use same index over and over 

thanks in advance

**Comment by aitboudad** [comment]
@uouo690 hi, can you fill a new issue with an example so I can provide you a better approach. Thanks!
